server:
  port: 8081
  session:
    cookie:
      name: UISESSION

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: html5
      clientSecret: password
      accessTokenUri: http://localhost:9191/uaa/oauth/token
      userAuthorizationUri: http://localhost:9191/uaa/oauth/authorize
    resource:
      userInfoUri: http://localhost:9191/uaa/user